package com.index.repository;

//Spring data for relational DB and no relational ones.

import org.springframework.data.repository.CrudRepository;

import com.index.model.Cat;


//@Repository this annotation is optional if we already set it uses CrudRepository
public interface CatRepository extends CrudRepository<Cat, Long> {

	// The implementation is generated by Spring Data framework, for the given
	// entity.

}
